import { useCallback, useEffect, useState } from 'react';
import { Bot, Save, ShieldCheck, Volume2 } from 'lucide-react';
import { automationApi } from './api';

interface AgentSettings {
  enabled: boolean; live2dEnabled: boolean; aiEnabled: boolean; voiceEnabled: boolean;
  config: { model: '22' | '33'; desktop: boolean; tablet: boolean; mobile: boolean; desktopSize: number; tabletSize: number; mobileSize: number; position: 'left' | 'right'; draggable: boolean; minimizable: boolean; hideable: boolean; voiceAutoplay: boolean; volume: number; speechRate: number; maxInputChars: number; maxOutputTokens: number; contextMessages: number; perMinute: number; perHour: number; perDay: number; guestPerDay: number; globalDailyCalls: number; globalDailyTokens: number; idleSeconds: number; personality: string; agentName: string; welcomeMessage: string; performanceProfile: 'high' | 'balanced' | 'economy' | 'fallback' };
}

export default function AdminVisualAgentPage() {
  const [value, setValue] = useState<AgentSettings | null>(null); const [message, setMessage] = useState(''); const [saving, setSaving] = useState(false);
  const load = useCallback(async () => { try { setValue(await automationApi<AgentSettings>('/api/admin/visual-agent/settings')); } catch (error) { setMessage(error instanceof Error ? error.message : 'Falha ao carregar.'); } }, []);
  useEffect(() => { void load(); }, [load]);
  async function save() { if (!value) return; setSaving(true); try { setValue(await automationApi<AgentSettings>('/api/admin/visual-agent/settings', { method: 'PATCH', body: JSON.stringify(value) })); setMessage('Configurações salvas.'); } catch (error) { setMessage(error instanceof Error ? error.message : 'Falha ao salvar.'); } finally { setSaving(false); } }
  if (!value) return <p className="text-slate-500">Carregando configurações do assistente…</p>;
  const updateConfig = (patch: Partial<AgentSettings['config']>) => setValue((current) => current ? { ...current, config: { ...current.config, ...patch } } : current);
  return <div className="space-y-6 text-slate-900">
    <header className="flex flex-col justify-between gap-4 sm:flex-row sm:items-start"><div><h2 className="flex items-center gap-2 text-2xl font-black"><Bot/>Assistente IA e Avatar Live2D</h2><p className="mt-1 text-slate-600">Controle independente do avatar, IA, voz, dispositivos e limites. A chave do provider nunca é exibida.</p></div><button type="button" onClick={save} disabled={saving} className="inline-flex min-h-11 items-center justify-center gap-2 rounded-xl bg-[#6535D9] px-5 font-black text-white disabled:opacity-50"><Save className="h-4 w-4"/>{saving ? 'Salvando…' : 'Salvar'}</button></header>
    {message && <p role="status" className="rounded-xl bg-violet-50 px-4 py-3 text-sm font-bold text-violet-800">{message}</p>}
    <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Toggle label="Assistente" checked={value.enabled} onChange={(checked) => setValue({ ...value, enabled: checked })}/><Toggle label="Live2D" checked={value.live2dEnabled} onChange={(checked) => setValue({ ...value, live2dEnabled: checked })}/><Toggle label="IA Groq" checked={value.aiEnabled} onChange={(checked) => setValue({ ...value, aiEnabled: checked })}/><Toggle label="Voz" checked={value.voiceEnabled} onChange={(checked) => setValue({ ...value, voiceEnabled: checked })}/></section>
    <div className="grid gap-6 lg:grid-cols-[1fr_320px]">
      <div className="space-y-6">
        <Card title="Modelo e dispositivos"><div className="grid gap-4 sm:grid-cols-3"><Field label="Modelo"><select value={value.config.model} onChange={(event) => updateConfig({ model: event.target.value as '22' | '33' })} className="input"><option value="22">22</option><option value="33">33</option></select></Field><Field label="Posição"><select value={value.config.position} onChange={(event) => updateConfig({ position: event.target.value as 'left' | 'right' })} className="input"><option value="right">Direita</option><option value="left">Esquerda</option></select></Field><Field label="Perfil de desempenho"><select value={value.config.performanceProfile} onChange={(event) => updateConfig({ performanceProfile: event.target.value as AgentSettings['config']['performanceProfile'] })} className="input"><option value="high">Alto</option><option value="balanced">Equilibrado</option><option value="economy">Economia</option><option value="fallback">Imagem estática</option></select></Field></div><div className="mt-4 grid gap-3 sm:grid-cols-3"><Toggle label="Desktop" checked={value.config.desktop} onChange={(desktop) => updateConfig({ desktop })}/><Toggle label="Tablet" checked={value.config.tablet} onChange={(tablet) => updateConfig({ tablet })}/><Toggle label="Mobile" checked={value.config.mobile} onChange={(mobile) => updateConfig({ mobile })}/></div></Card>
        <Card title="Comportamento e voz"><div className="grid gap-3 sm:grid-cols-2"><Toggle label="Permitir arrastar" checked={value.config.draggable} onChange={(draggable) => updateConfig({ draggable })}/><Toggle label="Permitir minimizar" checked={value.config.minimizable} onChange={(minimizable) => updateConfig({ minimizable })}/><Toggle label="Permitir ocultar" checked={value.config.hideable} onChange={(hideable) => updateConfig({ hideable })}/><Toggle label="Autoplay de voz" checked={value.config.voiceAutoplay} onChange={(voiceAutoplay) => updateConfig({ voiceAutoplay })}/></div><div className="mt-4 grid gap-4 sm:grid-cols-3"><NumberField label="Tamanho desktop" value={value.config.desktopSize} onChange={(desktopSize) => updateConfig({ desktopSize })}/><NumberField label="Tamanho tablet" value={value.config.tabletSize} onChange={(tabletSize) => updateConfig({ tabletSize })}/><NumberField label="Tamanho mobile" value={value.config.mobileSize} onChange={(mobileSize) => updateConfig({ mobileSize })}/></div></Card>
        <Card title="IA, contexto e limites"><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><NumberField label="Caracteres/mensagem" value={value.config.maxInputChars} onChange={(maxInputChars) => updateConfig({ maxInputChars })}/><NumberField label="Tokens/resposta" value={value.config.maxOutputTokens} onChange={(maxOutputTokens) => updateConfig({ maxOutputTokens })}/><NumberField label="Mensagens contexto" value={value.config.contextMessages} onChange={(contextMessages) => updateConfig({ contextMessages })}/><NumberField label="Mensagens/minuto" value={value.config.perMinute} onChange={(perMinute) => updateConfig({ perMinute })}/><NumberField label="Mensagens/hora" value={value.config.perHour} onChange={(perHour) => updateConfig({ perHour })}/><NumberField label="Mensagens/dia" value={value.config.perDay} onChange={(perDay) => updateConfig({ perDay })}/><NumberField label="Visitante/dia" value={value.config.guestPerDay} onChange={(guestPerDay) => updateConfig({ guestPerDay })}/><NumberField label="Chamadas globais/dia" value={value.config.globalDailyCalls} onChange={(globalDailyCalls) => updateConfig({ globalDailyCalls })}/><NumberField label="Tokens globais/dia" value={value.config.globalDailyTokens} onChange={(globalDailyTokens) => updateConfig({ globalDailyTokens })}/><NumberField label="Inatividade (s)" value={value.config.idleSeconds} onChange={(idleSeconds) => updateConfig({ idleSeconds })}/></div></Card>
        <Card title="Personalidade"><div className="grid gap-4 sm:grid-cols-2"><Field label="Nome"><input value={value.config.agentName} onChange={(event) => updateConfig({ agentName: event.target.value })} className="input"/></Field><Field label="Tom"><select value={value.config.personality} onChange={(event) => updateConfig({ personality: event.target.value })} className="input"><option value="profissional">Profissional</option><option value="amigável">Amigável</option><option value="objetivo">Objetivo</option></select></Field></div><Field label="Mensagem inicial"><textarea value={value.config.welcomeMessage} onChange={(event) => updateConfig({ welcomeMessage: event.target.value })} className="input mt-1 min-h-24 py-3"/></Field></Card>
      </div>
      <aside className="h-fit rounded-3xl bg-[#11132B] p-6 text-white shadow-xl"><p className="text-xs font-black uppercase tracking-[.2em] text-violet-300">Preview seguro</p><img src={`/live2d/fallbacks/${value.config.model}.svg`} alt={`Preview do modelo ${value.config.model}`} className="mx-auto mt-5 h-72 w-full object-contain"/><div className="mt-4 space-y-2 text-sm text-slate-300"><p className="flex gap-2"><ShieldCheck className="h-4 w-4 text-emerald-400"/>Assets permitidos pelo registry</p><p className="flex gap-2"><Volume2 className="h-4 w-4 text-violet-300"/>Autoplay desligado por padrão</p></div></aside>
    </div>
  </div>;
}

function Card({ title, children }: { title: string; children: React.ReactNode }) { return <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h3 className="mb-4 text-lg font-black">{title}</h3>{children}</section>; }
function Toggle({ label, checked, onChange }: { label: string; checked: boolean; onChange: (value: boolean) => void }) { return <label className="flex min-h-12 items-center justify-between gap-3 rounded-xl border border-slate-200 bg-slate-50 px-4 text-sm font-bold"><span>{label}</span><input type="checkbox" checked={checked} onChange={(event) => onChange(event.target.checked)} className="h-5 w-5 accent-violet-600"/></label>; }
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="block text-sm font-bold text-slate-700"><span>{label}</span>{children}</label>; }
function NumberField({ label, value, onChange }: { label: string; value: number; onChange: (value: number) => void }) { return <Field label={label}><input type="number" value={value} onChange={(event) => onChange(Number(event.target.value))} className="input"/></Field>; }
