import { useCallback, useEffect, useState } from 'react';
import { AlertTriangle, CheckCircle2, Pause, Play, Plus, RefreshCw, Workflow } from 'lucide-react';
import { automationApi, formatDate } from './api';

type Automation = { id:string; name:string; description?:string; status:string; trigger_type:string; current_version:number; risk_level:number; dry_run:boolean; runs:number; completed:number; failed:number; last_run_at?:string };
type Dashboard = { automations:{total:number;active:number}; runsToday:{total:number;completed:number;failed:number}; queue:{pending:number;dead_letter:number}; approvals:{pending:number}; settings:{key:string;value:boolean}[] };

export default function AdminAutomationsPage() {
  const [items,setItems]=useState<Automation[]>([]),[dashboard,setDashboard]=useState<Dashboard|null>(null),[error,setError]=useState(''),[loading,setLoading]=useState(true);
  const [creating,setCreating]=useState(false),[form,setForm]=useState({name:'',event:'lead.created',action:'notify_admins'});
  const load=useCallback(async()=>{setLoading(true);setError('');try{const [list,summary]=await Promise.all([automationApi<{automations:Automation[]}>('/api/admin/automations'),automationApi<Dashboard>('/api/admin/automations/dashboard')]);setItems(list.automations);setDashboard(summary)}catch(e){setError(e instanceof Error?e.message:'Falha ao carregar.')}finally{setLoading(false)}},[]);
  useEffect(()=>{void load()},[load]);
  const changeState=async(item:Automation)=>{try{await automationApi(`/api/admin/automations/${item.id}/${item.status==='active'?'pause':'activate'}`,{method:'POST'});await load()}catch(e){setError(e instanceof Error?e.message:'Falha ao alterar.') }};
  const setting=(key:string)=>Boolean(dashboard?.settings.find(x=>x.key===key)?.value);
  const toggle=async(key:string)=>{await automationApi('/api/admin/automations/settings',{method:'PATCH',body:JSON.stringify({key,value:!setting(key)})});await load()};
  const create=async(event:React.FormEvent)=>{event.preventDefault();try{await automationApi('/api/admin/automations',{method:'POST',body:JSON.stringify({name:form.name,triggerType:'event',triggerConfig:{events:[form.event]},conditions:{operator:'and',rules:[]},actions:[{id:'action-1',type:form.action,config:form.action==='notify_admins'?{title:form.name,message:'Evento de automação recebido.'}:{activityType:'task',title:form.name,dueInMinutes:60}}],dryRun:true,riskLevel:0})});setCreating(false);setForm({name:'',event:'lead.created',action:'notify_admins'});await load()}catch(e){setError(e instanceof Error?e.message:'Falha ao criar.')}};
  return <div className="space-y-6">
    <header className="flex flex-wrap items-start justify-between gap-4"><div><h2 className="flex items-center gap-2 text-2xl font-black"><Workflow/>Automações</h2><p className="text-gray-400">Orquestração baseada no outbox transacional, com versões, idempotência e controles de risco.</p></div><button onClick={()=>setCreating(x=>!x)} className="flex items-center gap-2 rounded-lg bg-violet-700 px-4 py-2 font-bold"><Plus className="h-4 w-4"/>Nova automação</button></header>
    {error&&<p role="alert" className="rounded-xl border border-red-800 bg-red-950/40 p-4 text-red-300">{error}</p>}
    <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{[['Ativas',dashboard?.automations.active],['Execuções hoje',dashboard?.runsToday.total],['Fila',dashboard?.queue.pending],['Aprovações',dashboard?.approvals.pending]].map(([label,value])=><div key={String(label)} className="rounded-xl border border-gray-800 bg-gray-900 p-4"><p className="text-sm text-gray-400">{label}</p><strong className="text-2xl">{value??'—'}</strong></div>)}</section>
    <section className="rounded-xl border border-gray-800 bg-gray-900 p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><h3 className="font-bold">Controles globais</h3><p className="text-sm text-gray-400">Ações externas e IA permanecem desligadas até configuração explícita.</p></div><button onClick={()=>void load()} className="rounded-lg border border-gray-700 p-2" aria-label="Atualizar"><RefreshCw className="h-4 w-4"/></button></div><div className="mt-4 flex flex-wrap gap-3">{[['automation.enabled','Motor'],['automation.external_actions_enabled','Ações externas'],['ai.enabled','IA']].map(([key,label])=><button key={key} onClick={()=>void toggle(key)} className={`rounded-full px-4 py-2 text-sm font-bold ${setting(key)?'bg-emerald-700':'bg-gray-700'}`}>{label}: {setting(key)?'ligado':'desligado'}</button>)}</div></section>
    {creating&&<form onSubmit={e=>void create(e)} className="grid gap-4 rounded-xl border border-violet-800 bg-gray-900 p-5 md:grid-cols-3"><label className="text-sm font-bold">Nome<input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})} className="mt-2 min-h-11 w-full rounded-lg border border-gray-700 bg-gray-950 px-3"/></label><label className="text-sm font-bold">Evento<input required pattern="[a-z][a-z0-9_.-]{2,100}" value={form.event} onChange={e=>setForm({...form,event:e.target.value})} className="mt-2 min-h-11 w-full rounded-lg border border-gray-700 bg-gray-950 px-3"/></label><label className="text-sm font-bold">Ação<select value={form.action} onChange={e=>setForm({...form,action:e.target.value})} className="mt-2 min-h-11 w-full rounded-lg border border-gray-700 bg-gray-950 px-3"><option value="notify_admins">Notificar administradores</option><option value="assign_lead">Atribuir lead</option><option value="create_crm_activity">Criar tarefa CRM</option></select></label><p className="text-sm text-gray-400 md:col-span-2">A nova regra nasce em rascunho e dry-run. Versões avançadas permanecem disponíveis pela API administrativa.</p><button className="min-h-11 rounded-lg bg-violet-700 font-bold">Criar rascunho seguro</button></form>}
    <section className="overflow-hidden rounded-xl border border-gray-800 bg-gray-900"><div className="overflow-x-auto"><table className="min-w-full text-sm"><thead className="bg-gray-800 text-left text-gray-300"><tr><th className="p-3">Automação</th><th className="p-3">Estado</th><th className="p-3">Versão/Risco</th><th className="p-3">Execuções</th><th className="p-3">Última</th><th className="p-3">Ação</th></tr></thead><tbody>{items.map(item=><tr key={item.id} className="border-t border-gray-800"><td className="p-3"><strong>{item.name}</strong><p className="max-w-md text-xs text-gray-400">{item.description}</p></td><td className="p-3">{item.status==='active'?<span className="text-emerald-400"><CheckCircle2 className="mr-1 inline h-4 w-4"/>Ativa</span>:<span className="text-amber-400"><AlertTriangle className="mr-1 inline h-4 w-4"/>{item.status}</span>}</td><td className="p-3">v{item.current_version} · {item.risk_level}</td><td className="p-3">{item.completed}/{item.runs} ({item.failed} falhas)</td><td className="p-3">{formatDate(item.last_run_at)}</td><td className="p-3"><button onClick={()=>void changeState(item)} className="rounded-lg border border-gray-700 p-2" aria-label={item.status==='active'?'Pausar':'Ativar'}>{item.status==='active'?<Pause className="h-4 w-4"/>:<Play className="h-4 w-4"/>}</button></td></tr>)}</tbody></table></div>{!loading&&items.length===0&&<p className="p-6 text-center text-gray-400">Nenhuma automação cadastrada.</p>}{loading&&<p className="p-6 text-center text-gray-400">Carregando…</p>}</section>
  </div>;
}
