import { Check, ChevronLeft, ExternalLink, MessageCircle } from 'lucide-react';
import { Link, useParams } from 'react-router-dom';
import Seo from '../components/seo/Seo';
import { getPortfolioProjectBySlug } from '../data/portfolio';
import { getWhatsAppLink } from '../utils/whatsapp';

export default function PortfolioDetailPage() {
  const { slug } = useParams();
  const project = getPortfolioProjectBySlug(slug);
  if (!project) return <main className="flex min-h-[70vh] items-center justify-center px-5 text-center"><div><h1 className="text-3xl font-black">Projeto não publicado</h1><p className="mt-3 text-slate-600">O projeto não existe ou ainda não possui autorização e conteúdo suficientes.</p><Link to="/portfolio" className="mt-6 inline-flex rounded-xl bg-[#5B4FE9] px-5 py-3 font-black text-white">Voltar ao portfólio</Link></div></main>;
  const whatsapp = getWhatsAppLink('orcamento', `Olá! Vi o projeto ${project.name} no portfólio da Nextia e gostaria de solicitar uma solução baseada nas necessidades da minha empresa.`);
  return <main className="min-h-screen bg-[#F7F8FC]"><Seo title={`${project.name} — Projeto desenvolvido | Nextia`} description={project.description} path={`/portfolio/${project.slug}`} /><section className="bg-[#11132B] pb-14 pt-28 text-white"><div className="mx-auto max-w-6xl px-5"><Link to="/portfolio" className="inline-flex items-center gap-2 text-violet-200"><ChevronLeft className="h-4 w-4" /> Portfólio</Link><span className="mt-8 block w-fit rounded-full bg-emerald-500/15 px-3 py-1 text-xs font-black text-emerald-300">Projeto realizado</span><h1 className="mt-4 text-4xl font-black sm:text-6xl">{project.name}</h1><p className="mt-5 max-w-3xl text-lg leading-8 text-slate-300">{project.description}</p></div></section><div className="mx-auto max-w-6xl space-y-8 px-5 py-14"><section className="grid gap-6 md:grid-cols-3"><Block title="Desafio" text={project.challenge} /><Block title="Solução" text={project.solution} /><Block title="Classificação" text={project.classification === 'client' ? 'Projeto para cliente' : 'Produto próprio Nextia'} /></section><section className="grid gap-6 sm:grid-cols-2">{project.images.map(image => <img key={image.src} src={image.src} alt={image.alt} loading="lazy" width="1200" height="750" className="rounded-2xl border border-slate-200" />)}</section><section className="grid gap-8 rounded-3xl bg-white p-7 md:grid-cols-2"><div><h2 className="text-2xl font-black">Recursos implementados</h2><List items={project.services} /></div><div><h2 className="text-2xl font-black">Resultados verificáveis</h2><List items={project.results} /></div></section><section className="rounded-3xl bg-violet-50 p-8 text-center"><h2 className="text-3xl font-black">Gostou deste projeto?</h2><p className="mt-3 text-slate-600">Podemos desenvolver uma solução baseada nas necessidades da sua empresa.</p><div className="mt-6 flex flex-col justify-center gap-3 sm:flex-row"><Link to={`/projeto-personalizado?source_page=portfolio&project=${project.slug}`} className="inline-flex min-h-12 items-center justify-center rounded-xl bg-[#5B4FE9] px-5 font-black text-white">Solicitar projeto semelhante</Link><a href={whatsapp} target="_blank" rel="noreferrer" className="inline-flex min-h-12 items-center justify-center gap-2 rounded-xl border border-[#5B4FE9] px-5 font-black text-[#5145D7]"><MessageCircle className="h-5 w-5" /> Falar no WhatsApp</a>{project.websiteUrl && <a href={project.websiteUrl} target="_blank" rel="noreferrer" className="inline-flex min-h-12 items-center justify-center gap-2 rounded-xl border border-slate-300 px-5 font-black"><ExternalLink className="h-5 w-5" /> Ver projeto</a>}</div></section></div></main>;
}
function Block({ title, text }: { title: string; text: string }) { return <article className="rounded-2xl border border-slate-200 bg-white p-6"><h2 className="text-sm font-black uppercase tracking-widest text-[#5B4FE9]">{title}</h2><p className="mt-3 leading-7 text-slate-700">{text}</p></article>; }
function List({ items }: { items: string[] }) { return <ul className="mt-5 space-y-3">{items.map(item => <li key={item} className="flex gap-2 text-slate-700"><Check className="mt-0.5 h-4 w-4 shrink-0 text-emerald-600" />{item}</li>)}</ul>; }
