import { ArrowRight, BriefcaseBusiness, LayoutTemplate, ShieldCheck } from 'lucide-react';
import { Link } from 'react-router-dom';
import Seo from '../components/seo/Seo';
import { getPublishedPortfolioProjects } from '../data/portfolio';

export default function PortfolioPage() {
  const projects = getPublishedPortfolioProjects();
  return <main className="min-h-screen bg-[#F7F8FC]">
    <Seo title="Portfólio de Sites, Sistemas e Automação | Nextia" description="Conheça projetos de sites, sistemas, automação e soluções digitais desenvolvidos pela Nextia." path="/portfolio" />
    <section className="bg-gradient-to-br from-[#0F0C29] to-[#1E1B4B] pb-16 pt-32 text-white"><div className="mx-auto max-w-7xl px-5 sm:px-8"><p className="text-sm font-black uppercase tracking-[.2em] text-violet-300">Trabalhos verificáveis</p><h1 className="mt-4 text-4xl font-black sm:text-6xl">Projetos Desenvolvidos pela Nextia</h1><p className="mt-5 max-w-3xl text-lg leading-8 text-slate-300">Conheça projetos e soluções desenvolvidos para diferentes necessidades. Publicamos somente trabalhos reais e autorizados.</p></div></section>
    <section className="mx-auto max-w-7xl px-5 py-14 sm:px-8"><div className="grid gap-5 md:grid-cols-2"><article className="rounded-3xl border border-violet-200 bg-violet-50 p-7"><LayoutTemplate className="h-8 w-8 text-[#5B4FE9]" /><h2 className="mt-4 text-2xl font-black">Modelos</h2><p className="mt-2 leading-7 text-slate-600">Bases de design disponíveis para contratação e personalização. Não representam clientes.</p><Link to="/modelos" className="mt-5 inline-flex items-center gap-2 font-black text-[#5145D7]">Ver modelos <ArrowRight className="h-4 w-4" /></Link></article><article className="rounded-3xl border border-emerald-200 bg-emerald-50 p-7"><BriefcaseBusiness className="h-8 w-8 text-emerald-700" /><h2 className="mt-4 text-2xl font-black">Portfólio</h2><p className="mt-2 leading-7 text-slate-600">Projetos realmente executados, publicados somente após validação e autorização.</p></article></div>
      {projects.length ? <div className="mt-10 grid gap-6 md:grid-cols-2 lg:grid-cols-3">{projects.map(project => <article key={project.id} className="overflow-hidden rounded-3xl border border-slate-200 bg-white"><img src={project.images[0].src} alt={project.images[0].alt} loading="lazy" width="800" height="500" className="aspect-[16/10] w-full object-cover" /><div className="p-6"><span className="rounded-full bg-emerald-100 px-3 py-1 text-xs font-black text-emerald-800">Projeto realizado</span><h2 className="mt-4 text-2xl font-black">{project.name}</h2><p className="mt-2 text-slate-600">{project.description}</p><Link to={`/portfolio/${project.slug}`} className="mt-5 inline-flex items-center gap-2 font-black text-[#5145D7]">Ver detalhes <ArrowRight className="h-4 w-4" /></Link></div></article>)}</div> : <div className="mt-10 rounded-3xl border border-dashed border-slate-300 bg-white px-6 py-16 text-center"><ShieldCheck className="mx-auto h-12 w-12 text-[#5B4FE9]" /><h2 className="mt-5 text-2xl font-black">Portfólio em validação</h2><p className="mx-auto mt-3 max-w-2xl leading-7 text-slate-600">Ainda não há projetos com autorização e material visual completo para publicação. Nenhum cliente, resultado ou case fictício será exibido para preencher esta área.</p><Link to="/modelos" className="mt-7 inline-flex min-h-11 items-center rounded-xl bg-[#5B4FE9] px-5 font-black text-white">Conhecer modelos disponíveis</Link></div>}
    </section>
  </main>;
}
