import { useMemo, useState } from 'react';
import { ArrowLeft, CheckCircle2, Loader2, Send } from 'lucide-react';
import { Link, Navigate, useSearchParams } from 'react-router-dom';
import { useServiceCatalog } from '../hooks/useServiceCatalog';
import Seo from '../components/seo/Seo';

export default function ServiceRequestPage() {
  const [params] = useSearchParams();
  const services = useServiceCatalog();
  const service = useMemo(() => services.find((item) => item.slug === params.get('service')), [params, services]);
  const requestedItem = params.get('item') || service?.name || '';
  const [form, setForm] = useState({ name: '', email: '', phone: '', company: '', city: '', details: '' });
  const [loading, setLoading] = useState(false); const [error, setError] = useState('');
  const [result, setResult] = useState<{ trackingLink: string; routedToTechnician: boolean } | null>(null);
  if (!service) return <Navigate to="/solucoes" replace />;
  const change = (field: keyof typeof form, value: string) => setForm((current) => ({ ...current, [field]: value }));
  const submit = async (event: React.FormEvent) => {
    event.preventDefault(); setLoading(true); setError('');
    try {
      const response = await fetch('/api/service-requests', { method: 'POST', credentials: 'include', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ serviceSlug: service.slug, requestedItem, ...form }) });
      const data = await response.json(); if (!response.ok) throw new Error(data.error || 'Não foi possível enviar a solicitação.');
      setResult(data);
    } catch (err) { setError(err instanceof Error ? err.message : 'Falha ao enviar solicitação.'); } finally { setLoading(false); }
  };
  if (result) return <main className="min-h-screen bg-[#F4F8FC] px-5 pb-20 pt-32"><Seo title="Solicitação recebida" description="Solicitação de serviço recebida pela Nextia." noindex /><div className="mx-auto max-w-2xl rounded-3xl border border-slate-200 bg-white p-8 text-center shadow-xl sm:p-12"><CheckCircle2 className="mx-auto h-16 w-16 text-green-600" /><h1 className="mt-5 text-3xl font-black">Solicitação registrada</h1><p className="mt-4 text-lg leading-8 text-slate-600">O serviço <strong>{requestedItem}</strong> foi enviado para o painel administrativo{result.routedToTechnician ? ' e para a fila técnica' : ''}. Se você já possui uma conta com este e-mail, a solicitação também aparecerá no seu painel.</p><div className="mt-8 flex flex-col justify-center gap-3 sm:flex-row"><a href={result.trackingLink} className="inline-flex min-h-12 items-center justify-center rounded-xl bg-[#1677FF] px-6 font-bold text-white">Acompanhar solicitação</a><Link to="/" className="inline-flex min-h-12 items-center justify-center rounded-xl border border-slate-300 px-6 font-bold">Voltar ao início</Link></div></div></main>;
  return <main className="min-h-screen bg-[#F4F8FC] px-5 pb-20 pt-28 sm:px-8"><Seo title={`Solicitar ${requestedItem}`} description={`Solicite ${requestedItem} à equipe Nextia.`} noindex /><div className="mx-auto max-w-5xl"><Link to={`/${service.slug}`} className="inline-flex min-h-11 items-center gap-2 font-bold text-slate-600"><ArrowLeft className="h-5 w-5" /> Voltar</Link><div className="mt-5 grid gap-6 lg:grid-cols-[.7fr_1.3fr]"><aside className="h-max rounded-2xl bg-[#07162B] p-7 text-white"><p className="text-sm font-bold" style={{ color: service.accent }}>{service.eyebrow}</p><h1 className="mt-2 text-3xl font-black">{requestedItem}</h1><p className="mt-4 text-base leading-7 text-slate-300">{service.summary}</p><ul className="mt-6 space-y-3">{service.benefits.slice(0,4).map((item)=><li key={item} className="flex gap-2 text-sm"><CheckCircle2 className="h-5 w-5 shrink-0" style={{color:service.accent}} />{item}</li>)}</ul></aside><form onSubmit={submit} className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm sm:p-8"><p className="font-bold text-[#1677FF]">Solicitação de serviço</p><h2 className="mt-2 text-2xl font-black">Conte como podemos ajudar</h2><p className="mt-2 text-slate-600">Não é necessário criar uma conta agora. Use o mesmo e-mail da sua conta Nextia para vincular a solicitação ao painel.</p><div className="mt-7 grid gap-5 sm:grid-cols-2">{([['name','Nome completo *'],['email','E-mail *'],['phone','Telefone / WhatsApp *'],['company','Empresa'],['city','Cidade']] as const).map(([field,label])=><label key={field} className="font-bold text-slate-700">{label}<input required={['name','email','phone'].includes(field)} type={field === 'email' ? 'email' : 'text'} value={form[field]} onChange={(e)=>change(field,e.target.value)} maxLength={field === 'email' ? 320 : 200} className="mt-2 min-h-12 w-full rounded-xl border border-slate-300 px-4 font-normal" /></label>)}</div><label className="mt-5 block font-bold text-slate-700">Detalhes da necessidade *<textarea required value={form.details} onChange={(e)=>change('details',e.target.value)} maxLength={5000} rows={6} className="mt-2 w-full rounded-xl border border-slate-300 p-4 font-normal" placeholder="Descreva o cenário, quantidade de equipamentos, prazo ou objetivo esperado." /></label>{error && <div className="mt-5 rounded-xl border border-red-200 bg-red-50 p-4 text-red-700">{error}</div>}<button disabled={loading} className="mt-6 inline-flex min-h-13 w-full items-center justify-center gap-2 rounded-xl bg-gradient-to-r from-[#2563FF] to-[#753AFF] px-6 text-lg font-extrabold text-white disabled:opacity-60">{loading ? <Loader2 className="h-5 w-5 animate-spin" /> : <Send className="h-5 w-5" />}{loading ? 'Enviando...' : 'Enviar solicitação'}</button></form></div></div></main>;
}
