import { useEffect, useMemo, useState } from 'react';
import { Check, ChevronLeft, ChevronRight, ExternalLink, Maximize2, MessageCircle, Monitor, Smartphone, Tablet, X } from 'lucide-react';
import { Link, useParams, useSearchParams } from 'react-router-dom';
import Seo from '../components/seo/Seo';
import TemplateCard from '../components/templates/TemplateCard';
import { getTemplateMetadata, isPublishedTemplate } from '../data/templateMetadata';
import { getTemplateServiceSlug, templates } from '../data/templates';
import { getWhatsAppLink, trackEvent } from '../utils/whatsapp';

type Viewport = 'desktop' | 'tablet' | 'mobile';

export default function TemplateDetailPage() {
  const { slug } = useParams();
  const [searchParams] = useSearchParams();
  const template = templates.find(item => item.slug === slug);
  const [viewport, setViewport] = useState<Viewport>('desktop');
  const [lightbox, setLightbox] = useState(false);
  const metadata = useMemo(() => template ? getTemplateMetadata(template) : null, [template]);

  useEffect(() => { if (template && metadata) trackEvent('view_template', { template_id: template.slug, segment: template.categorySlug, type: metadata.type }); window.scrollTo(0, 0); }, [template, metadata]);
  useEffect(() => { if (!lightbox) return; const close = (event: KeyboardEvent) => event.key === 'Escape' && setLightbox(false); window.addEventListener('keydown', close); return () => window.removeEventListener('keydown', close); }, [lightbox]);

  const related = useMemo(() => template ? templates.filter(item => item.slug !== template.slug && isPublishedTemplate(item)).sort((a, b) => Number(b.categorySlug === template.categorySlug) - Number(a.categorySlug === template.categorySlug)).slice(0, 3) : [], [template]);
  if (!template || !metadata || !isPublishedTemplate(template)) return <main className="flex min-h-[70vh] items-center justify-center px-5 text-center"><div><h1 className="text-3xl font-black">Modelo indisponível</h1><p className="mt-3 text-slate-600">Este modelo não está publicado ou ainda não possui conteúdo completo.</p><Link to="/modelos" className="mt-6 inline-flex min-h-11 items-center rounded-xl bg-[#5B4FE9] px-5 font-bold text-white">Ver modelos publicados</Link></div></main>;

  const context = new URLSearchParams(searchParams);
  context.set('service', getTemplateServiceSlug(template)); context.set('template', template.slug); context.set('plano', template.recommendedPlan.toLowerCase()); context.set('source_page', 'template'); context.set('segment', template.categorySlug);
  const whatsapp = getWhatsAppLink('sites', `Olá! Gostei do modelo ${template.name} (ID: ${template.slug}) no site da Nextia e gostaria de saber como contratar e personalizá-lo para minha empresa. Segmento: ${template.category}. URL: https://nextia.dev.br/modelos/${template.slug}`);
  const width = viewport === 'desktop' ? 'w-full' : viewport === 'tablet' ? 'mx-auto w-[72%]' : 'mx-auto w-[42%] min-w-[260px]';
  const image = template.previewDesktop || template.coverImage;

  return <main className="min-h-screen bg-[#F7F8FC] pb-20">
    <Seo title={`Modelo de Site para ${template.category} | ${template.name} | Nextia`} description={`Conheça o modelo ${template.name}, desenvolvido para ${template.category.toLocaleLowerCase('pt-BR')}. Veja a demonstração e personalize seu site com a Nextia.`} path={`/modelos/${template.slug}`} image={template.coverImage} />
    <section className="bg-gradient-to-br from-[#0F0C29] to-[#1E1B4B] pb-14 pt-28 text-white"><div className="mx-auto max-w-7xl px-5 sm:px-8"><Link to="/modelos" className="inline-flex items-center gap-2 text-sm font-bold text-violet-200"><ChevronLeft className="h-4 w-4" /> Modelos</Link><div className="mt-8 grid items-center gap-10 lg:grid-cols-[.8fr_1.2fr]"><div><div className="flex flex-wrap gap-2"><span className="rounded-full bg-violet-500/20 px-3 py-1 text-xs font-black text-violet-200">Modelo disponível</span><span className="rounded-full border border-white/15 px-3 py-1 text-xs font-bold">{template.category}</span><span className="rounded-full border border-white/15 px-3 py-1 text-xs font-bold">{metadata.style}</span></div><h1 className="mt-5 text-4xl font-black sm:text-5xl">{template.name}</h1><p className="mt-4 text-lg leading-8 text-slate-300">{template.description}</p><div className="mt-7 flex flex-col gap-3 sm:flex-row">{template.demoUrl && template.demoUrl !== '#' && <Link to={template.demoUrl} onClick={() => trackEvent('open_template_demo', { template_id: template.slug, segment: template.categorySlug, type: metadata.type })} className="inline-flex min-h-12 items-center justify-center gap-2 rounded-xl bg-white px-5 font-black text-[#352A9B]"><ExternalLink className="h-5 w-5" /> Ver demonstração</Link>}<Link to={`/cadastro?${context}`} onClick={() => trackEvent('select_template', { template_id: template.slug, segment: template.categorySlug, type: metadata.type })} className="inline-flex min-h-12 items-center justify-center rounded-xl bg-[#6D4AFF] px-5 font-black text-white">Quero este modelo</Link></div></div><Preview template={template} image={image} viewport={viewport} width={width} setViewport={setViewport} open={() => setLightbox(true)} /></div></div></section>
    <div className="mx-auto max-w-7xl space-y-8 px-5 py-14 sm:px-8">
      <section className="grid gap-6 lg:grid-cols-3"><Info title="Ideal para" items={[template.category]} /><Info title="Tipo" items={[metadata.type]} /><Info title="Plano associado" items={[template.recommendedPlan, 'Valores carregados do plano no fluxo de contratação']} /></section>
      <section className="grid gap-8 rounded-3xl border border-slate-200 bg-white p-6 sm:p-8 lg:grid-cols-2"><div><h2 className="text-2xl font-black">Páginas sugeridas</h2><List items={template.pages} /></div><div><h2 className="text-2xl font-black">Recursos desta estrutura</h2><List items={template.features} /></div></section>
      <section className="grid gap-8 rounded-3xl bg-[#11132B] p-6 text-white sm:p-8 lg:grid-cols-2"><div><p className="text-sm font-black uppercase tracking-widest text-violet-300">Personalização básica</p><h2 className="mt-3 text-3xl font-black">Personalize para sua empresa</h2><p className="mt-3 leading-7 text-slate-300">A base visual recebe a identidade e o conteúdo da sua marca. Alterações estruturais profundas podem exigir orçamento específico.</p><List items={metadata.customizationOptions} dark /></div><div><p className="text-sm font-black uppercase tracking-widest text-emerald-300">Nextia 360</p><h2 className="mt-3 text-3xl font-black">Leve este projeto além do site</h2><List items={metadata.availableAddons} dark /><Link to="/solucoes" className="mt-6 inline-flex items-center gap-2 font-black text-violet-300">Conhecer Nextia 360 <ChevronRight className="h-5 w-5" /></Link></div></section>
      <section><h2 className="text-3xl font-black">Você também pode gostar</h2><div className="mt-7 grid gap-6 md:grid-cols-2 xl:grid-cols-3">{related.map(item => <TemplateCard key={item.id} template={item} />)}</div></section>
      <section className="rounded-3xl border border-violet-200 bg-violet-50 p-8 text-center"><h2 className="text-3xl font-black">Pronto para personalizar este modelo?</h2><p className="mx-auto mt-3 max-w-2xl text-slate-600">O modelo e o segmento já seguem identificados para você não precisar escolher tudo novamente.</p><div className="mt-7 flex flex-col justify-center gap-3 sm:flex-row"><Link to={`/cadastro?${context}`} className="inline-flex min-h-12 items-center justify-center rounded-xl bg-[#5B4FE9] px-6 font-black text-white">Quero este modelo</Link><a href={whatsapp} target="_blank" rel="noreferrer" onClick={() => trackEvent('generate_lead', { source_page: 'template', template_id: template.slug, segment: template.categorySlug })} className="inline-flex min-h-12 items-center justify-center gap-2 rounded-xl border border-[#5B4FE9] px-6 font-black text-[#5145D7]"><MessageCircle className="h-5 w-5" /> Falar no WhatsApp</a></div></section>
    </div>
    <div className="fixed inset-x-0 bottom-0 z-40 flex gap-2 border-t border-slate-200 bg-white/95 p-3 shadow-2xl backdrop-blur md:hidden"><a href={whatsapp} className="inline-flex min-h-12 flex-1 items-center justify-center gap-2 rounded-xl border border-[#5B4FE9] font-black text-[#5145D7]"><MessageCircle className="h-5 w-5" /> WhatsApp</a><Link to={`/cadastro?${context}`} className="inline-flex min-h-12 flex-1 items-center justify-center rounded-xl bg-[#5B4FE9] font-black text-white">Quero este modelo</Link></div>
    {lightbox && <div role="dialog" aria-modal="true" aria-label={`Visual ampliado de ${template.name}`} className="fixed inset-0 z-50 flex items-center justify-center bg-black/90 p-4" onClick={() => setLightbox(false)}><button aria-label="Fechar" className="absolute right-5 top-5 rounded-full bg-white p-3" onClick={() => setLightbox(false)}><X className="h-5 w-5" /></button><img src={image} alt={`Tela inicial do modelo ${template.name} em versão ${viewport}`} className="max-h-[88vh] max-w-[94vw] object-contain" onClick={event => event.stopPropagation()} /></div>}
  </main>;
}

function Preview({ template, image, viewport, width, setViewport, open }: { template: ReturnType<typeof templates.find> extends infer T ? NonNullable<T> : never; image: string; viewport: Viewport; width: string; setViewport: (value: Viewport) => void; open: () => void }) {
  const choices: Array<[Viewport, typeof Monitor, string]> = [['desktop', Monitor, 'Desktop'], ['tablet', Tablet, 'Tablet'], ['mobile', Smartphone, 'Mobile']];
  return <div><div className="mb-3 flex flex-wrap gap-2">{choices.map(([value, Icon, label]) => <button key={value} onClick={() => setViewport(value)} aria-pressed={viewport === value} className={`inline-flex min-h-10 items-center gap-2 rounded-xl px-3 text-sm font-bold ${viewport === value ? 'bg-white text-[#352A9B]' : 'bg-white/10 text-white'}`}><Icon className="h-4 w-4" />{label}</button>)}</div><button onClick={open} aria-label="Ampliar visual do modelo" className={`group relative block overflow-hidden rounded-2xl border-[6px] border-slate-800 bg-white shadow-2xl transition-all ${width}`}><img src={image} alt={`Tela inicial do modelo ${template.name} em versão ${viewport}`} className="aspect-[16/10] w-full object-cover object-top" loading="eager" width="960" height="600" /><span className="absolute bottom-3 right-3 rounded-full bg-black/70 p-2 text-white opacity-0 transition group-hover:opacity-100"><Maximize2 className="h-5 w-5" /></span></button></div>;
}
function Info({ title, items }: { title: string; items: string[] }) { return <article className="rounded-2xl border border-slate-200 bg-white p-6"><h2 className="text-sm font-black uppercase tracking-widest text-[#5B4FE9]">{title}</h2>{items.map(item => <p key={item} className="mt-3 font-bold text-slate-800">{item}</p>)}</article>; }
function List({ items, dark = false }: { items: string[]; dark?: boolean }) { return <ul className="mt-5 grid gap-3 sm:grid-cols-2">{items.map(item => <li key={item} className={`flex gap-2 text-sm ${dark ? 'text-slate-200' : 'text-slate-700'}`}><Check className="mt-0.5 h-4 w-4 shrink-0 text-emerald-500" />{item}</li>)}</ul>; }
