import { CalendarDays, CheckCircle2, Clock3, MapPin, Menu, MessageCircle, ShieldCheck, Sparkles } from 'lucide-react';
import { segmentPresets, type PreviewContent } from './acquisitionPresets';

export type PreviewPage = 'inicio' | 'servicos' | 'agendamento' | 'contato';
export type AcquisitionPreview = { segment_slug: string; template_slug: string; business_name: string; theme: { primaryColor?: string }; content: PreviewContent; revision: number; expires_at?: string };

export default function PreviewSite({ preview, page, onPage, device = 'desktop' }: { preview: AcquisitionPreview; page: PreviewPage; onPage: (page: PreviewPage) => void; device?: 'desktop' | 'mobile' }) {
  const preset = segmentPresets[preview.segment_slug] || segmentPresets['prestadores-de-servicos'];
  const rawServices = preview.content?.services?.length ? preview.content.services : preset.content.services;
  const content = { ...preset.content, ...(preview.content || {}), services: rawServices.map((item, index) => typeof item === 'string' ? { title: item, description: preset.content.services[index]?.description || '' } : item) };
  const primary = preview.theme?.primaryColor || preset.accent;
  const mobile = device === 'mobile';
  const goWhatsApp = `https://wa.me/${String(content.whatsapp || '').replace(/\D/g, '')}`;

  return <div className="relative min-h-[620px] overflow-hidden bg-white text-slate-950">
    <header className={`flex items-center justify-between border-b border-slate-200 bg-white ${mobile ? 'px-4 py-4' : 'px-7 py-5'}`}>
      <div><strong className={`${mobile ? 'text-base' : 'text-xl'} font-black tracking-tight`}>{preview.business_name}</strong><span className="mt-0.5 block text-[9px] font-bold uppercase tracking-[.2em]" style={{ color: primary }}>{preset.name}</span></div>
      {mobile ? <button className="rounded-lg border border-slate-200 p-2" aria-label="Abrir menu"><Menu className="h-4 w-4" /></button> : <nav className="flex items-center gap-1 text-xs font-bold">{(['inicio','servicos','agendamento','contato'] as PreviewPage[]).map((item)=><button key={item} onClick={()=>onPage(item)} className="rounded-lg px-3 py-2 capitalize" style={{color:page===item?primary:'#64748b',background:page===item?`${primary}12`:'transparent'}}>{item === 'agendamento' ? preset.bookingLabel : item}</button>)}</nav>}
    </header>

    {page === 'inicio' && <>
      <section className={`grid overflow-hidden ${mobile ? 'grid-cols-1' : 'grid-cols-[1.02fr_.98fr]'}`} style={{ background: `linear-gradient(135deg,${primary}12,#fff 62%)` }}>
        <div className={`${mobile ? 'order-2 px-5 py-8' : 'px-10 py-14'}`}>
          <span className="inline-flex items-center gap-2 text-[10px] font-black uppercase tracking-[.22em]" style={{color:primary}}><Sparkles className="h-3.5 w-3.5" />{content.eyebrow}</span>
          <h1 className={`mt-4 font-black leading-[1.05] tracking-[-.035em] ${mobile ? 'text-3xl' : 'text-5xl'}`}>{content.headline}</h1>
          <p className={`mt-5 max-w-xl leading-7 text-slate-600 ${mobile ? 'text-sm' : 'text-base'}`}>{content.description}</p>
          <div className={`mt-7 flex ${mobile ? 'flex-col' : 'flex-wrap'} gap-3`}><button onClick={()=>onPage('agendamento')} className="rounded-xl px-5 py-3 text-sm font-extrabold text-white" style={{background:primary}}>{content.cta}</button><button onClick={()=>onPage('servicos')} className="rounded-xl border border-slate-300 bg-white px-5 py-3 text-sm font-extrabold">Conhecer serviços</button></div>
          <div className={`mt-7 flex ${mobile ? 'flex-col gap-2' : 'gap-5'} text-[11px] font-semibold text-slate-500`}>{['Site seguro','Atendimento rápido','Experiência mobile'].map(item=><span key={item} className="flex items-center gap-1.5"><CheckCircle2 className="h-3.5 w-3.5" style={{color:primary}}/>{item}</span>)}</div>
        </div>
        <div className={`relative ${mobile ? 'order-1 h-56' : 'min-h-[440px]'}`}><img src={preset.image} alt={`Modelo de site para ${preset.name}`} className="absolute inset-0 h-full w-full object-cover"/><div className="absolute inset-0 bg-gradient-to-t from-black/55 via-transparent to-transparent"/><div className="absolute bottom-5 left-5 right-5 rounded-2xl border border-white/20 bg-black/45 p-4 text-white backdrop-blur"><span className="text-[10px] font-bold uppercase tracking-[.2em]">Atendimento facilitado</span><strong className="mt-1 block text-lg">WhatsApp, localização e agenda integrados</strong></div></div>
      </section>
      <section className={`${mobile ? 'px-5 py-9' : 'px-10 py-12'}`}><div className={`grid gap-6 ${mobile ? 'grid-cols-1' : 'grid-cols-[.8fr_1.2fr]'}`}><div><span className="text-xs font-black uppercase tracking-[.2em]" style={{color:primary}}>Sobre nós</span><h2 className={`${mobile?'text-2xl':'text-3xl'} mt-3 font-black`}>{content.aboutTitle}</h2></div><p className="leading-7 text-slate-600">{content.aboutText}</p></div><div className={`mt-8 grid gap-3 ${mobile ? 'grid-cols-1' : 'grid-cols-3'}`}>{content.services.slice(0,3).map((service)=><article key={service.title} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><span className="flex h-9 w-9 items-center justify-center rounded-xl" style={{background:`${primary}18`,color:primary}}><CheckCircle2 className="h-5 w-5"/></span><strong className="mt-4 block">{service.title}</strong><p className="mt-2 text-sm leading-6 text-slate-500">{service.description}</p></article>)}</div></section>
    </>}

    {page === 'servicos' && <section className={`${mobile ? 'p-5' : 'p-10'}`}><span className="text-xs font-black uppercase tracking-[.2em]" style={{color:primary}}>Feito para o seu segmento</span><h2 className={`${mobile?'text-3xl':'text-4xl'} mt-3 font-black`}>{content.servicesTitle}</h2><p className="mt-3 max-w-2xl text-slate-600">Uma estrutura completa para informar, gerar confiança e transformar visitas em contatos reais.</p><div className={`mt-8 grid gap-4 ${mobile ? 'grid-cols-1' : 'grid-cols-3'}`}>{content.services.map((service,index)=><article key={`${service.title}-${index}`} className="rounded-2xl border border-slate-200 p-5"><span className="text-3xl font-black opacity-20" style={{color:primary}}>0{index+1}</span><strong className="mt-4 block text-lg">{service.title}</strong><p className="mt-2 text-sm leading-6 text-slate-500">{service.description}</p><button onClick={()=>onPage('agendamento')} className="mt-5 text-sm font-extrabold" style={{color:primary}}>Tenho interesse →</button></article>)}</div></section>}

    {page === 'agendamento' && <section className={`${mobile ? 'p-5' : 'p-10'}`} style={{background:`linear-gradient(140deg,${primary}10,#fff)`}}><div className={`mx-auto grid max-w-4xl gap-6 ${mobile ? 'grid-cols-1' : 'grid-cols-[.8fr_1.2fr]'}`}><div><span className="flex h-12 w-12 items-center justify-center rounded-2xl text-white" style={{background:primary}}><CalendarDays className="h-6 w-6"/></span><h2 className={`${mobile?'text-3xl':'text-4xl'} mt-5 font-black`}>{content.bookingTitle}</h2><p className="mt-4 leading-7 text-slate-600">{content.bookingText}</p><div className="mt-6 space-y-3 text-sm text-slate-600"><span className="flex items-center gap-2"><Clock3 className="h-4 w-4" style={{color:primary}}/>Confirmação rápida</span><span className="flex items-center gap-2"><MessageCircle className="h-4 w-4" style={{color:primary}}/>Lembrete pelo WhatsApp</span><span className="flex items-center gap-2"><ShieldCheck className="h-4 w-4" style={{color:primary}}/>Seus dados protegidos</span></div></div><div className="rounded-3xl border border-slate-200 bg-white p-6 shadow-xl shadow-slate-900/5"><label className="block text-xs font-bold text-slate-600">Serviço<select className="mt-2 w-full rounded-xl border border-slate-300 bg-white p-3"><option>{content.services[0]?.title}</option>{content.services.slice(1).map(item=><option key={item.title}>{item.title}</option>)}</select></label><div className={`mt-4 grid gap-3 ${mobile?'grid-cols-1':'grid-cols-2'}`}><label className="text-xs font-bold text-slate-600">Data<input type="date" className="mt-2 w-full rounded-xl border border-slate-300 p-3"/></label><label className="text-xs font-bold text-slate-600">Horário<select className="mt-2 w-full rounded-xl border border-slate-300 bg-white p-3"><option>09:00</option><option>14:00</option><option>16:30</option></select></label></div><button className="mt-5 w-full rounded-xl py-3 font-extrabold text-white" style={{background:primary}}>{content.bookingButton}</button><p className="mt-3 text-center text-[10px] text-slate-400">Demonstração: nenhuma solicitação será enviada.</p></div></div></section>}

    {page === 'contato' && <section className={`${mobile ? 'p-5' : 'p-10'}`}><div className={`grid overflow-hidden rounded-3xl border border-slate-200 ${mobile?'grid-cols-1':'grid-cols-2'}`}><div className="p-7"><span className="text-xs font-black uppercase tracking-[.2em]" style={{color:primary}}>Contato e localização</span><h2 className="mt-3 text-3xl font-black">Vamos conversar?</h2><p className="mt-3 text-sm leading-6 text-slate-600">Fale com a equipe de {preview.business_name} ou visite nosso endereço.</p><div className="mt-6 space-y-3 text-sm"><span className="flex items-center gap-2"><MessageCircle className="h-4 w-4" style={{color:primary}}/>{content.phone}</span><span className="flex items-center gap-2"><MapPin className="h-4 w-4" style={{color:primary}}/>{content.address}</span></div><a href={goWhatsApp} target="_blank" rel="noreferrer" className="mt-6 inline-flex rounded-xl px-5 py-3 text-sm font-extrabold text-white" style={{background:'#16a34a'}}>Conversar no WhatsApp</a></div><iframe title={`Mapa de ${preview.business_name}`} src={`https://www.google.com/maps?q=${encodeURIComponent(content.address)}&output=embed`} className={`${mobile?'h-60':'min-h-[360px]'} w-full border-0`} loading="lazy" referrerPolicy="no-referrer-when-downgrade"/></div></section>}

    <a href={goWhatsApp} target="_blank" rel="noreferrer" aria-label="Falar pelo WhatsApp" className="absolute bottom-4 right-4 flex h-12 w-12 items-center justify-center rounded-full bg-green-600 text-white shadow-xl"><MessageCircle className="h-6 w-6"/></a>
  </div>;
}
