import { useEffect, useMemo, useState } from 'react';
import { AlertTriangle, ArrowLeft, CheckCircle2, Clock3, Loader2, Plus, Save, Trash2 } from 'lucide-react';
import { Link, useParams } from 'react-router-dom';

type Hour={weekday:number;start_time:string;end_time:string}; type Off={starts_at:string;ends_at:string;reason?:string};
type Tech={user_id:string;name:string;email:string;phone?:string;company?:string;professional_title?:string;bio?:string;technical_level?:string;employment_status?:string;availability_status?:string;accepts_remote?:boolean;accepts_onsite?:boolean;max_simultaneous_tickets?:number;home_city?:string;home_state?:string;service_radius_km?:number;service_cities?:string[];notes?:string;specialties?:string[];authorized_services?:string[];working_hours?:Hour[];time_off?:Off[];active_tickets:number};
type Opt={id?:string;slug?:string;name:string;category?:string}; type Ticket={id:string;subject:string;name:string;company?:string;priority:string;status:string;created_at:string};
const tabs=['Perfil','Especialidades','Serviços','Disponibilidade','Agenda base','Chamados'] as const; const days=['Domingo','Segunda','Terça','Quarta','Quinta','Sexta','Sábado'];
const availability:Record<string,string>={AVAILABLE:'🟢 Disponível',BUSY:'🔵 Ocupado',ON_ROUTE:'🟠 Em deslocamento',IN_SERVICE:'🔵 Em atendimento',BREAK:'🟡 Pausa',ABSENT:'⚪ Ausente',OFFLINE:'⚫ Offline',INACTIVE:'🔴 Inativo'};
const localDate=(value:string)=>value?new Date(value).toISOString().slice(0,16):'';

export default function AdminTechnicianDetailPage(){
 const {userId}=useParams(); const [tech,setTech]=useState<Tech|null>(null),[specs,setSpecs]=useState<Opt[]>([]),[services,setServices]=useState<Opt[]>([]),[tickets,setTickets]=useState<Ticket[]>([]); const [tab,setTab]=useState<(typeof tabs)[number]>('Perfil'),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState(''),[success,setSuccess]=useState('');
 useEffect(()=>{fetch(`/api/admin/technicians/detail?userId=${encodeURIComponent(userId||'')}`,{credentials:'include',cache:'no-store'}).then(async r=>{const d=await r.json();if(!r.ok)throw Error(d.error);setTech({...d.technician,technical_level:d.technician.technical_level||'JUNIOR',employment_status:d.technician.employment_status||'ACTIVE',availability_status:d.technician.availability_status||'OFFLINE',accepts_remote:d.technician.accepts_remote!==false,accepts_onsite:d.technician.accepts_onsite===true,max_simultaneous_tickets:d.technician.max_simultaneous_tickets||4,specialties:d.technician.specialties||[],authorized_services:d.technician.authorized_services||[],service_cities:d.technician.service_cities||[],working_hours:d.technician.working_hours||[],time_off:d.technician.time_off||[]});setSpecs(d.specialties);setServices(d.services);setTickets(d.tickets)}).catch(e=>setError(e.message)).finally(()=>setLoading(false))},[userId]);
 const completeness=useMemo(()=>tech?Math.round([tech.professional_title,tech.home_city,tech.home_state,tech.specialties?.length,tech.authorized_services?.length,tech.working_hours?.length].filter(Boolean).length/6*100):0,[tech]);
 const overlaps=useMemo(()=>{if(!tech)return false;return (tech.working_hours||[]).some((a,i,all)=>all.some((b,j)=>i!==j&&a.weekday===b.weekday&&a.start_time<b.end_time&&b.start_time<a.end_time))},[tech]);
 const invalidOff=useMemo(()=>Boolean(tech?.time_off?.some(o=>!o.starts_at||!o.ends_at||new Date(o.ends_at)<=new Date(o.starts_at))),[tech]);
 const change=(v:Partial<Tech>)=>setTech(t=>t?{...t,...v}:t); const toggle=(field:'specialties'|'authorized_services',value:string)=>change({[field]:tech?.[field]?.includes(value)?tech[field]!.filter(x=>x!==value):[...(tech?.[field]||[]),value]});
 const save=async()=>{if(!tech||overlaps||invalidOff)return;setSaving(true);setError('');setSuccess('');try{const r=await fetch('/api/admin/technicians/save',{method:'POST',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify({userId:tech.user_id,professionalTitle:tech.professional_title,bio:tech.bio,technicalLevel:tech.technical_level,employmentStatus:tech.employment_status,availabilityStatus:tech.availability_status,acceptsRemote:tech.accepts_remote,acceptsOnsite:tech.accepts_onsite,maxSimultaneousTickets:tech.max_simultaneous_tickets,homeCity:tech.home_city,homeState:tech.home_state,serviceRadiusKm:tech.service_radius_km,serviceCities:tech.service_cities?.map(x=>x.trim()).filter(Boolean),specialties:tech.specialties,authorizedServices:tech.authorized_services,workingHours:tech.working_hours?.map(h=>({weekday:h.weekday,startTime:h.start_time.slice(0,5),endTime:h.end_time.slice(0,5)})),timeOff:tech.time_off?.map(o=>({startsAt:o.starts_at,endsAt:o.ends_at,reason:o.reason})),notes:tech.notes})});const d=await r.json();if(!r.ok)throw Error(d.error);setSuccess('Perfil profissional salvo.')}catch(e){setError(e instanceof Error?e.message:'Falha ao salvar.')}finally{setSaving(false)}};
 if(loading)return <div className="flex min-h-64 items-center justify-center gap-2"><Loader2 className="h-5 w-5 animate-spin"/>Carregando técnico...</div>; if(!tech)return <div className="border border-red-200 bg-red-50 p-5 text-red-700">{error||'Técnico não encontrado.'}</div>;
 return <div className="space-y-6"><Link to="/admin/tecnicos" className="inline-flex items-center gap-2 font-bold text-slate-600"><ArrowLeft className="h-4 w-4"/>Equipe técnica</Link><header className="rounded-2xl border bg-white p-6"><div className="flex flex-col justify-between gap-5 lg:flex-row lg:items-center"><div><p className="font-bold text-[#1677FF]">{tech.professional_title||'Perfil profissional'}</p><h1 className="text-3xl font-black">{tech.name}</h1><p className="text-slate-500">{tech.email} · {availability[tech.availability_status||'OFFLINE']}</p></div><div className="grid grid-cols-3 gap-3 text-center"><Stat label="Completude" value={`${completeness}%`}/><Stat label="Ativos" value={`${tech.active_tickets}/${tech.max_simultaneous_tickets}`}/><Stat label="Modalidade" value={tech.accepts_remote&&tech.accepts_onsite?'Ambas':tech.accepts_onsite?'Local':'Remota'}/></div></div></header>
 <nav className="flex gap-2 overflow-x-auto rounded-2xl border bg-white p-2">{tabs.map(item=><button key={item} onClick={()=>setTab(item)} className={`min-h-11 shrink-0 rounded-xl px-4 font-bold ${tab===item?'bg-[#1677FF] text-white':'text-slate-600 hover:bg-slate-50'}`}>{item}</button>)}</nav>{error&&<Notice error text={error}/>} {success&&<Notice text={success}/>} {(overlaps||invalidOff)&&<Notice error text={overlaps?'Existem horários sobrepostos no mesmo dia.':'Todo bloqueio precisa de início e fim válidos.'}/>}<section className="rounded-2xl border bg-white p-6">
 {tab==='Perfil'&&<div className="grid gap-5 sm:grid-cols-2"><Field label="Título profissional"><input value={tech.professional_title||''} onChange={e=>change({professional_title:e.target.value})}/></Field><Field label="Nível"><select value={tech.technical_level} onChange={e=>change({technical_level:e.target.value})}><option>JUNIOR</option><option>PLENO</option><option>SENIOR</option><option>SPECIALIST</option></select></Field><Field label="Vínculo profissional"><select value={tech.employment_status} onChange={e=>change({employment_status:e.target.value})}><option value="ACTIVE">Ativo</option><option value="ON_LEAVE">Afastado</option><option value="INACTIVE">Inativo</option></select></Field><Field label="Capacidade simultânea"><input type="number" min="1" max="100" value={tech.max_simultaneous_tickets} onChange={e=>change({max_simultaneous_tickets:Number(e.target.value)})}/></Field><Field label="Biografia"><textarea rows={4} value={tech.bio||''} onChange={e=>change({bio:e.target.value})}/></Field><Field label="Notas internas"><textarea rows={4} value={tech.notes||''} onChange={e=>change({notes:e.target.value})}/></Field></div>}
 {tab==='Especialidades'&&<ChoiceGrid options={specs} selected={tech.specialties||[]} onToggle={v=>toggle('specialties',v)} idKey="id"/>}
 {tab==='Serviços'&&<ChoiceGrid options={services} selected={tech.authorized_services||[]} onToggle={v=>toggle('authorized_services',v)} idKey="slug"/>}
 {tab==='Disponibilidade'&&<div className="grid gap-5 sm:grid-cols-2"><Field label="Status atual"><select value={tech.availability_status} onChange={e=>change({availability_status:e.target.value})}>{Object.entries(availability).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></Field><div className="flex items-center gap-6"><label className="font-bold"><input type="checkbox" checked={tech.accepts_remote} onChange={e=>change({accepts_remote:e.target.checked})}/> Atendimento remoto</label><label className="font-bold"><input type="checkbox" checked={tech.accepts_onsite} onChange={e=>change({accepts_onsite:e.target.checked})}/> Presencial</label></div><Field label="Cidade base"><input value={tech.home_city||''} onChange={e=>change({home_city:e.target.value})}/></Field><Field label="UF"><input maxLength={2} value={tech.home_state||''} onChange={e=>change({home_state:e.target.value})}/></Field><Field label="Raio de atendimento (km)"><input type="number" min="0" value={tech.service_radius_km??''} onChange={e=>change({service_radius_km:e.target.value===''?undefined:Number(e.target.value)})}/></Field><ListEditor title="Cidades específicas" onAdd={()=>change({service_cities:[...(tech.service_cities||[]),'']})}>{tech.service_cities?.map((city,i)=><EditRow key={i} onDelete={()=>change({service_cities:tech.service_cities!.filter((_,j)=>j!==i)})}><input value={city} onChange={e=>change({service_cities:tech.service_cities!.map((x,j)=>j===i?e.target.value:x)})} placeholder="Cidade - UF"/></EditRow>)}</ListEditor></div>}
 {tab==='Agenda base'&&<div className="grid gap-8 lg:grid-cols-2"><ListEditor title="Horários semanais" onAdd={()=>change({working_hours:[...(tech.working_hours||[]),{weekday:1,start_time:'08:00',end_time:'18:00'}]})}>{tech.working_hours?.map((h,i)=><EditRow key={i} onDelete={()=>change({working_hours:tech.working_hours!.filter((_,j)=>j!==i)})}><select value={h.weekday} onChange={e=>change({working_hours:tech.working_hours!.map((x,j)=>j===i?{...x,weekday:Number(e.target.value)}:x)})}>{days.map((d,j)=><option key={d} value={j}>{d}</option>)}</select><input type="time" value={h.start_time.slice(0,5)} onChange={e=>change({working_hours:tech.working_hours!.map((x,j)=>j===i?{...x,start_time:e.target.value}:x)})}/><input type="time" value={h.end_time.slice(0,5)} onChange={e=>change({working_hours:tech.working_hours!.map((x,j)=>j===i?{...x,end_time:e.target.value}:x)})}/></EditRow>)}</ListEditor><ListEditor title="Bloqueios futuros" onAdd={()=>change({time_off:[...(tech.time_off||[]),{starts_at:'',ends_at:'',reason:''}]})}>{tech.time_off?.map((o,i)=><EditRow key={i} onDelete={()=>change({time_off:tech.time_off!.filter((_,j)=>j!==i)})}><input type="datetime-local" value={localDate(o.starts_at)} onChange={e=>change({time_off:tech.time_off!.map((x,j)=>j===i?{...x,starts_at:e.target.value}:x)})}/><input type="datetime-local" value={localDate(o.ends_at)} onChange={e=>change({time_off:tech.time_off!.map((x,j)=>j===i?{...x,ends_at:e.target.value}:x)})}/><input value={o.reason||''} onChange={e=>change({time_off:tech.time_off!.map((x,j)=>j===i?{...x,reason:e.target.value}:x)})} placeholder="Férias, folga, bloqueio..."/></EditRow>)}</ListEditor></div>}
 {tab==='Chamados'&&<div className="overflow-x-auto"><table className="w-full min-w-[720px] text-left"><thead><tr className="border-b text-sm uppercase text-slate-500"><th className="p-3">Chamado</th><th className="p-3">Cliente</th><th className="p-3">Prioridade</th><th className="p-3">Status</th><th className="p-3">Data</th></tr></thead><tbody>{tickets.map(t=><tr key={t.id} className="border-b"><td className="p-3 font-bold">{t.subject}</td><td className="p-3">{t.name}{t.company&&` · ${t.company}`}</td><td className="p-3">{t.priority}</td><td className="p-3">{t.status}</td><td className="p-3">{new Date(t.created_at).toLocaleDateString('pt-BR')}</td></tr>)}</tbody></table>{!tickets.length&&<p className="py-10 text-center text-slate-500">Nenhum chamado atribuído.</p>}<Link to="/admin/suporte" className="mt-5 inline-flex font-bold text-[#1677FF]">Abrir gestão de suporte</Link></div>}
 </section>{tab!=='Chamados'&&<button onClick={save} disabled={saving||overlaps||invalidOff} className="flex min-h-12 w-full items-center justify-center gap-2 rounded-xl bg-[#1677FF] font-bold text-white disabled:opacity-50">{saving?<Loader2 className="h-5 w-5 animate-spin"/>:<Save className="h-5 w-5"/>}Salvar alterações</button>}</div>;
}

function Stat({label,value}:{label:string;value:string}){return <div className="rounded-xl bg-slate-50 px-4 py-3"><p className="text-xs text-slate-500">{label}</p><p className="font-black">{value}</p></div>}
function Notice({text,error=false}:{text:string;error?:boolean}){return <div className={`flex gap-2 border p-4 ${error?'border-red-200 bg-red-50 text-red-700':'border-green-200 bg-green-50 text-green-700'}`}>{error?<AlertTriangle className="h-5 w-5"/>:<CheckCircle2 className="h-5 w-5"/>}{text}</div>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="font-bold">{label}<span className="mt-2 block [&>*]:min-h-11 [&>*]:w-full [&>*]:rounded [&>*]:border [&>*]:p-3 [&>*]:font-normal">{children}</span></label>}
function ChoiceGrid({options,selected,onToggle,idKey}:{options:Opt[];selected:string[];onToggle:(v:string)=>void;idKey:'id'|'slug'}){return <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{options.map(o=>{const id=o[idKey]!;return <button key={id} onClick={()=>onToggle(id)} className={`flex min-h-14 items-center gap-3 rounded-xl border p-4 text-left font-bold ${selected.includes(id)?'border-[#1677FF] bg-blue-50 text-[#1677FF]':'border-slate-200'}`}><span className={`h-5 w-5 rounded border ${selected.includes(id)?'bg-[#1677FF]':''}`}/>{o.name}</button>})}</div>}
function ListEditor({title,onAdd,children}:{title:string;onAdd:()=>void;children:React.ReactNode}){return <section><div className="flex items-center justify-between"><h3 className="text-lg font-black">{title}</h3><button onClick={onAdd} className="inline-flex items-center gap-1 font-bold text-[#1677FF]"><Plus className="h-4 w-4"/>Adicionar</button></div><div className="mt-3 space-y-3">{children}</div></section>}
function EditRow({children,onDelete}:{children:React.ReactNode;onDelete:()=>void}){return <div className="grid gap-2 rounded-xl border bg-slate-50 p-3 [&_input]:min-h-11 [&_input]:rounded [&_input]:border [&_input]:px-3 [&_select]:min-h-11 [&_select]:rounded [&_select]:border [&_select]:px-3"><div className="grid gap-2 sm:grid-cols-3">{children}</div><button onClick={onDelete} className="inline-flex items-center gap-1 text-sm font-bold text-red-600"><Trash2 className="h-4 w-4"/>Remover</button></div>}
