import { useEffect, useState } from 'react';
import { Archive, Check, Copy, Loader2, Pencil, Plus, Save } from 'lucide-react';

interface ModelRow { id: string; slug: string; service_slug: string; name: string; category: string; description: string; cover_image: string; preview_url: string; features: string[]; featured: boolean; active: boolean; price_cents: number; activation_fee_cents: number; sort_order: number; }
const empty: ModelRow = { id: '', slug: '', service_slug: 'sites-prontos', name: '', category: '', description: '', cover_image: '', preview_url: '', features: [], featured: false, active: false, price_cents: 0, activation_fee_cents: 0, sort_order: 0 };

export default function AdminModelsPage() {
  const [rows, setRows] = useState<ModelRow[]>([]); const [form, setForm] = useState<ModelRow>(empty); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState(''); const [saved, setSaved] = useState(false);
  const load = async () => { setLoading(true); setError(''); try { const response = await fetch('/api/admin/catalog/store-templates', { credentials: 'include', cache: 'no-store' }); const data = await response.json(); if (!response.ok) throw new Error(data.error || 'Falha ao carregar modelos.'); setRows(data.templates || []); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Falha ao carregar modelos.'); } finally { setLoading(false); } };
  // Sincronização inicial com a fonte administrativa remota.
  // eslint-disable-next-line react-hooks/set-state-in-effect
  useEffect(() => { void load(); }, []);
  const edit = (row: ModelRow) => { setForm({ ...row, features: Array.isArray(row.features) ? row.features : [] }); setSaved(false); window.scrollTo({ top: 0, behavior: 'smooth' }); };
  const save = async (model = form) => { setSaving(true); setError(''); setSaved(false); try { const response = await fetch('/api/admin/catalog/store-templates', { method: 'POST', credentials: 'include', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ id: model.id || undefined, slug: model.slug, serviceSlug: model.service_slug, name: model.name, category: model.category, description: model.description, coverImage: model.cover_image, previewUrl: model.preview_url, features: model.features, featured: model.featured, active: model.active, priceCents: model.price_cents, activationFeeCents: model.activation_fee_cents, sortOrder: model.sort_order }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error || 'Falha ao salvar modelo.'); setSaved(true); setForm(empty); await load(); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Falha ao salvar modelo.'); } finally { setSaving(false); } };
  const duplicate = (row: ModelRow) => edit({ ...row, id: '', slug: `${row.slug}-copia`, name: `${row.name} — cópia`, active: false, featured: false });
  return <div className="space-y-8"><header><h2 className="text-2xl font-black">Modelos de Sites</h2><p className="mt-2 text-slate-600">Cadastre, edite, duplique, ordene, destaque, publique ou arquive modelos. Preços permanecem ligados ao catálogo comercial.</p></header>{error && <p role="alert" className="border border-red-200 bg-red-50 p-4 font-bold text-red-700">{error}</p>}{saved && <p className="flex items-center gap-2 border border-emerald-200 bg-emerald-50 p-4 font-bold text-emerald-700"><Check className="h-5 w-5" /> Modelo salvo.</p>}
    <section className="rounded-2xl border border-slate-200 bg-white p-6"><div className="flex items-center justify-between"><h3 className="text-xl font-black">{form.id ? 'Editar modelo' : 'Novo modelo'}</h3>{form.id && <button onClick={() => setForm(empty)} className="font-bold text-[#1677FF]"><Plus className="inline h-4 w-4" /> Novo</button>}</div><div className="mt-5 grid gap-4 md:grid-cols-2"><Field label="Nome" value={form.name} onChange={name => setForm(current => ({ ...current, name }))} /><Field label="Slug" value={form.slug} onChange={slug => setForm(current => ({ ...current, slug }))} /><Field label="Segmento" value={form.category} onChange={category => setForm(current => ({ ...current, category }))} /><label className="font-bold text-slate-700">Produto associado<select value={form.service_slug} onChange={event => setForm(current => ({ ...current, service_slug: event.target.value }))} className="mt-1 min-h-11 w-full rounded border border-slate-300 px-3"><option value="sites-prontos">Sites prontos</option><option value="lojas-virtuais">Lojas virtuais</option></select></label><Field label="Imagem principal" value={form.cover_image} onChange={cover_image => setForm(current => ({ ...current, cover_image }))} /><Field label="URL da demonstração" value={form.preview_url} onChange={preview_url => setForm(current => ({ ...current, preview_url }))} /><label className="md:col-span-2 font-bold text-slate-700">Descrição<textarea value={form.description} onChange={event => setForm(current => ({ ...current, description: event.target.value }))} rows={3} className="mt-1 w-full rounded border border-slate-300 p-3" /></label><label className="md:col-span-2 font-bold text-slate-700">Recursos, um por linha<textarea value={form.features.join('\n')} onChange={event => setForm(current => ({ ...current, features: event.target.value.split('\n').map(value => value.trim()).filter(Boolean) }))} rows={4} className="mt-1 w-full rounded border border-slate-300 p-3" /></label><Field label="Ordem" type="number" value={String(form.sort_order)} onChange={sort_order => setForm(current => ({ ...current, sort_order: Number(sort_order) }))} /><div className="flex items-center gap-6 pt-7"><Toggle label="Publicado" checked={form.active} onChange={active => setForm(current => ({ ...current, active }))} /><Toggle label="Destaque" checked={form.featured} onChange={featured => setForm(current => ({ ...current, featured }))} /></div></div><button disabled={saving || !form.name || !form.slug || !form.description} onClick={() => void save()} className="mt-6 inline-flex min-h-11 items-center gap-2 rounded bg-[#1677FF] px-5 font-black text-white disabled:opacity-50">{saving ? <Loader2 className="h-5 w-5 animate-spin" /> : <Save className="h-5 w-5" />} Salvar modelo</button></section>
    <section className="overflow-x-auto rounded-2xl border border-slate-200 bg-white">{loading ? <p className="p-8 text-center">Carregando...</p> : <table className="w-full min-w-[900px] text-left"><thead className="bg-slate-50 text-sm uppercase text-slate-500"><tr><th className="p-4">Modelo</th><th className="p-4">Produto</th><th className="p-4">Status</th><th className="p-4">Ordem</th><th className="p-4 text-right">Ações</th></tr></thead><tbody className="divide-y">{rows.map(row => <tr key={row.id}><td className="p-4"><strong>{row.name}</strong><p className="text-sm text-slate-500">/{row.slug} · {row.category}</p></td><td className="p-4">{row.service_slug}</td><td className="p-4"><span className={`rounded-full px-3 py-1 text-xs font-black ${row.active ? 'bg-emerald-100 text-emerald-700' : 'bg-slate-200 text-slate-600'}`}>{row.active ? 'Publicado' : 'Arquivado'}</span></td><td className="p-4">{row.sort_order}</td><td className="p-4"><div className="flex justify-end gap-2"><Action title="Editar" onClick={() => edit(row)} icon={Pencil} /><Action title="Duplicar" onClick={() => duplicate(row)} icon={Copy} /><Action title="Arquivar" onClick={() => void save({ ...row, active: false })} icon={Archive} /></div></td></tr>)}</tbody></table>}</section>
  </div>;
}
function Field({ label, value, onChange, type = 'text' }: { label: string; value: string; onChange: (value: string) => void; type?: string }) { return <label className="font-bold text-slate-700">{label}<input type={type} value={value} onChange={event => onChange(event.target.value)} className="mt-1 min-h-11 w-full rounded border border-slate-300 px-3" /></label>; }
function Toggle({ label, checked, onChange }: { label: string; checked: boolean; onChange: (value: boolean) => void }) { return <label className="flex items-center gap-2 font-bold"><input type="checkbox" checked={checked} onChange={event => onChange(event.target.checked)} className="h-5 w-5" />{label}</label>; }
function Action({ title, onClick, icon: Icon }: { title: string; onClick: () => void; icon: typeof Pencil }) { return <button title={title} aria-label={title} onClick={onClick} className="rounded border border-slate-300 p-2 hover:bg-slate-50"><Icon className="h-4 w-4" /></button>; }
