import { useEffect, useState } from 'react';
import { Loader2, Save } from 'lucide-react';

interface PlanRow { id: string; name: string; monthly_amount_cents: number; activation_amount_cents: number; active: boolean; sort_order: number; }

export default function AdminPlansPage() {
  const [plans, setPlans] = useState<PlanRow[]>([]); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(''); const [error, setError] = useState('');
  useEffect(() => { fetch('/api/admin/catalog/plans', { credentials: 'include', cache: 'no-store' }).then(async (response) => { const data = await response.json(); if (!response.ok) throw new Error(data.error); setPlans(data.plans); }).catch((err) => setError(err.message || 'Falha ao carregar planos.')).finally(() => setLoading(false)); }, []);
  const change = (id: string, values: Partial<PlanRow>) => setPlans((current) => current.map((plan) => plan.id === id ? { ...plan, ...values } : plan));
  const save = async (plan: PlanRow) => { setSaving(plan.id); setError(''); try { const response = await fetch('/api/admin/catalog/plans', { method: 'PATCH', credentials: 'include', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ id: plan.id, monthlyAmountCents: plan.monthly_amount_cents, activationAmountCents: plan.activation_amount_cents, active: plan.active, sortOrder: plan.sort_order }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error); change(plan.id, data.plan); } catch (err) { setError(err instanceof Error ? err.message : 'Falha ao salvar.'); } finally { setSaving(''); } };
  if (loading) return <div className="flex min-h-64 items-center justify-center gap-2 text-slate-500"><Loader2 className="h-5 w-5 animate-spin" /> Carregando planos...</div>;
  return <div className="space-y-6"><header><h2 className="text-2xl font-black text-slate-900">Planos digitais</h2><p className="mt-2 text-base text-slate-600">Gerencie os valores usados na página comercial e no checkout.</p></header>{error && <div className="border border-red-200 bg-red-50 p-4 text-red-700">{error}</div>}<div className="grid gap-5 lg:grid-cols-3">{plans.map((plan) => <article key={plan.id} className="border border-slate-200 bg-white p-6"><h3 className="text-xl font-black">{plan.name}</h3><div className="mt-6 space-y-4"><label className="block text-base font-bold">Mensalidade<input type="number" min="0.01" step="0.01" value={(plan.monthly_amount_cents / 100).toFixed(2)} onChange={(event) => change(plan.id, { monthly_amount_cents: Math.round(Number(event.target.value) * 100) })} className="mt-2 w-full rounded border border-slate-300 px-3 py-2" /></label><label className="block text-base font-bold">Taxa de ativação<input type="number" min="0.01" step="0.01" value={(plan.activation_amount_cents / 100).toFixed(2)} onChange={(event) => change(plan.id, { activation_amount_cents: Math.round(Number(event.target.value) * 100) })} className="mt-2 w-full rounded border border-slate-300 px-3 py-2" /></label><label className="flex min-h-11 items-center gap-3 text-base font-bold"><input type="checkbox" checked={plan.active} onChange={(event) => change(plan.id, { active: event.target.checked })} className="h-5 w-5 accent-[#1677FF]" />Publicado</label><button onClick={() => save(plan)} disabled={saving === plan.id} className="inline-flex min-h-11 w-full items-center justify-center gap-2 rounded bg-[#1677FF] px-4 font-bold text-white disabled:opacity-60">{saving === plan.id ? <Loader2 className="h-4 w-4 animate-spin" /> : <Save className="h-4 w-4" />} Salvar plano</button></div></article>)}</div></div>;
}
